# xphi.kernel.space.time.Dockerfile.xphi
FROM ghcr.io/catthehacker/ubuntu:act-latest
RUN apt-get update && apt-get install -y \
    curl \
    wget \
    jq \
    unzip \
    zip \
    git \
    build-essential \
    libffi-dev \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

ENV DENO_INSTALL=/root/.deno
ENV PATH="$DENO_INSTALL/bin:$PATH"
RUN curl -fsSL https://deno.land/install.sh | sh