[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "xphi"
version = "1.0.1"
description = "The Universal Integration Boundary for heterogeneous AI ecosystems"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "uvloop", "redis", "networkx", "pyyaml", "watchdog", "rocksdict", "libcst", "pydantic", "httpx", "eclipse-zenoh"
]

[project.scripts]
anchor-bind = "brane.anchor.bind.around:run_around"

[tool.hatch.build.targets.wheel]
packages = ["xphi"]