FROM python:3.12-slim

RUN apt-get update && apt-get install -y curl git jq build-essential sudo unzip && rm -rf /var/lib/apt/lists/*
RUN groupadd -g 1001 runner && \
    useradd -u 1001 -g 1001 -m -s /bin/bash runner && \
    echo "runner ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

RUN mkdir -p /artifact_mount && chown -R runner:runner /artifact_mount

USER runner
ENV HOME=/home/runner

ENV VIRTUAL_ENV="$HOME/.venv"
ENV PATH="$VIRTUAL_ENV/bin:$HOME/.local/bin:$HOME/.deno/bin:$PATH"

RUN curl -fsSL https://deno.land/install.sh | sh && \
    curl -LsSf https://astral.sh/uv/install.sh | sh && \
    $HOME/.local/bin/uv venv $VIRTUAL_ENV

RUN uv pip install build hatch && \
    uv pip install git+https://github.com/wittgena/fiber.git

## missing packages temp install    
RUN uv pip install tinytag dataclasses_json requests deprecated Pillow tiktoken PyNaCl psutil
WORKDIR $HOME
RUN python -m xphi.kernel.space.bind.around